

/* Create Tables */

CREATE TABLE CASE_MARK
(
	CASE_MARK_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '事件符号ID',
	CASE_MARK_NAME VARCHAR(10) NOT NULL COMMENT '事件符号名',
	CASE_MARK_ALIAS VARCHAR(10) NOT NULL COMMENT '事件符号別名',
	CASE_CATEGORY_CODE VARCHAR(10) NOT NULL COMMENT '事件カテゴリーコード',
	COURT_TYPE_CODE VARCHAR(10) COMMENT '裁判所種別コード',
	CASE_MARK_DETAIL VARCHAR(100) COMMENT '事件符号詳細',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (CASE_MARK_ID)
) COMMENT = '事件符号';


CREATE TABLE CLS_BENCH
(
	BENCH_CODE VARCHAR(10) NOT NULL COMMENT '法廷種別コード',
	BENCH_NAME VARCHAR(10) NOT NULL UNIQUE COMMENT '法廷種別名',
	BENCH_ALIAS VARCHAR(10) NOT NULL UNIQUE COMMENT '法廷種別別名',
	DESCRIPTION TEXT NOT NULL COMMENT '説明 : 説明',
	DISPLAY_ORDER INT UNSIGNED NOT NULL UNIQUE COMMENT '順番 : 順番',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (BENCH_CODE)
) COMMENT = '[区分値]法廷種別';


CREATE TABLE CLS_CASE_CATEGORY
(
	CASE_CATEGORY_CODE VARCHAR(10) NOT NULL COMMENT '事件カテゴリーコード',
	CASE_CATEGORY_NAME VARCHAR(10) NOT NULL UNIQUE COMMENT '事件カテゴリー名',
	CASE_CATEGORY_ALIAS VARCHAR(30) NOT NULL UNIQUE COMMENT '事件カテゴリー別名',
	DESCRIPTION TEXT NOT NULL COMMENT '説明 : 説明',
	DISPLAY_ORDER INT UNSIGNED NOT NULL UNIQUE COMMENT '順番 : 順番',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (CASE_CATEGORY_CODE)
) COMMENT = '[区分値]事件カテゴリー';


CREATE TABLE CLS_COURT_TYPE
(
	COURT_TYPE_CODE VARCHAR(10) NOT NULL COMMENT '裁判所種別コード',
	COURT_TYPE_NAME VARCHAR(10) NOT NULL UNIQUE COMMENT '裁判所種別名',
	COURT_TYPE_ALIAS VARCHAR(10) NOT NULL UNIQUE COMMENT '裁判所種別別名',
	DESCRIPTION TEXT NOT NULL COMMENT '説明 : 説明',
	DISPLAY_ORDER INT UNSIGNED NOT NULL UNIQUE COMMENT '順番 : 順番',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (COURT_TYPE_CODE)
) COMMENT = '[区分値]裁判所種別';


CREATE TABLE CLS_ERA
(
	ERA_CODE VARCHAR(10) NOT NULL COMMENT '元号コード',
	ERA_NAME VARCHAR(10) NOT NULL UNIQUE COMMENT '元号名',
	ERA_ALIAS VARCHAR(10) NOT NULL UNIQUE COMMENT '元号別名',
	DESCRIPTION TEXT NOT NULL COMMENT '説明 : 説明',
	DISPLAY_ORDER INT UNSIGNED NOT NULL UNIQUE COMMENT '順番 : 順番',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (ERA_CODE)
) COMMENT = '[区分値]元号';


CREATE TABLE CLS_JUDGEMENT_RESULT
(
	JUDGEMENT_RESULT_CODE VARCHAR(10) NOT NULL COMMENT '判決結果コード',
	JUDGEMENT_RESULT_NAME VARCHAR(10) NOT NULL UNIQUE COMMENT '判決結果名',
	JUDGEMENT_RESULT_ALIAS VARCHAR(10) NOT NULL UNIQUE COMMENT '判決結果別名',
	DESCRIPTION TEXT NOT NULL COMMENT '説明 : 説明',
	DISPLAY_ORDER INT UNSIGNED NOT NULL UNIQUE COMMENT '順番 : 順番',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (JUDGEMENT_RESULT_CODE)
) COMMENT = '[区分値]判決結果';


CREATE TABLE CLS_JUDGEMENT_TYPE
(
	JUDGEMENT_TYPE_CODE VARCHAR(10) NOT NULL COMMENT '判決種別コード',
	JUDGEMENT_TYPE_NAME VARCHAR(10) NOT NULL UNIQUE COMMENT '判決種別名',
	JUDGEMENT_TYPE_ALIAS VARCHAR(10) NOT NULL UNIQUE COMMENT '判決種別別名',
	DESCRIPTION TEXT NOT NULL COMMENT '説明 : 説明',
	DISPLAY_ORDER INT UNSIGNED NOT NULL UNIQUE COMMENT '順番 : 順番',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (JUDGEMENT_TYPE_CODE)
) COMMENT = '[区分値]判決種別';


CREATE TABLE CLS_USER_STATUS
(
	USER_STATUS_CODE VARCHAR(10) NOT NULL COMMENT 'ユーザーステータスコード',
	USER_STATUS_NAME VARCHAR(10) NOT NULL COMMENT 'ユーザーステータス名',
	USER_STATUS_ALIAS VARCHAR(10) NOT NULL COMMENT 'ユーザーステータス別名',
	DESCRIPTION TEXT NOT NULL COMMENT '説明 : 説明',
	DISPLAY_ORDER INT UNSIGNED NOT NULL UNIQUE COMMENT '順番 : 順番',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (USER_STATUS_CODE)
) COMMENT = '[区分値]ユーザーステータス';


CREATE TABLE COURT
(
	COURT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '裁判所ID',
	COURT_NAME VARCHAR(100) NOT NULL UNIQUE COMMENT '裁判所名',
	COURT_ALIAS VARCHAR(100) NOT NULL UNIQUE COMMENT '裁判所別名',
	COURT_TYPE_CODE VARCHAR(10) NOT NULL COMMENT '裁判所種別コード',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (COURT_ID)
) COMMENT = '裁判所';


CREATE TABLE COURT_SCRAPE_RESULT
(
	COURT_SCRAPE_RESULT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '裁判所スクレイピング結果ID',
	CASE_NUMBER VARCHAR(50) NOT NULL UNIQUE COMMENT '事件番号',
	CASE_NAME TEXT COMMENT '事件名',
	JUDGEMENT_DATE VARCHAR(50) COMMENT '裁判年月日',
	COURT_NAME VARCHAR(50) COMMENT '裁判所名',
	JUDGEMENT_TYPE VARCHAR(50) COMMENT '裁判種別',
	JUDGEMENT_RESULT VARCHAR(50) COMMENT '結果',
	PRECEDENT_REPORTS VARCHAR(50) COMMENT '判例集',
	ORIGINAL_COURT_NAME VARCHAR(50) COMMENT '原審裁判所名',
	ORIGINAL_CASE_NUMBER VARCHAR(50) COMMENT '原審事件番号',
	ORIGINAL_JUDGEMENT_DATE VARCHAR(50) COMMENT '原審裁判年月日',
	ORIGINAL_JUDGEMENT_RESULT VARCHAR(100) COMMENT '原審結果',
	JUDGEMENT_CONTENT TEXT COMMENT '判示事項',
	JUDGEMENT_SUMMARY TEXT COMMENT '裁判要旨',
	LAW TEXT COMMENT '参照法条',
	TEXT_URL VARCHAR(150) COMMENT '全文URL',
	HIGH_COURT_REPORTS VARCHAR(50) COMMENT '高裁判例集',
	JUDGEMENT_CONTENT_SUMMARY TEXT COMMENT '判示事項の要旨',
	RIGHT_TYPE TEXT COMMENT '権利種別',
	LAWSUIT_TYPE VARCHAR(200) COMMENT '訴訟類型',
	CASE_CATEGORY VARCHAR(100) COMMENT '事件分野',
	SOURCE_ORIGINAL_ID INT UNSIGNED NOT NULL UNIQUE COMMENT '取得元ID : URL末尾のID。最大6桁。',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (COURT_SCRAPE_RESULT_ID)
) COMMENT = '裁判所スクレイピング結果 : 裁判所からスクレイピングした結果を格納';


CREATE TABLE JUDGEMENT
(
	JUDGEMENT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '判決ID',
	JUDGEMENT_PUBLIC_CODE VARCHAR(20) NOT NULL UNIQUE COMMENT '判決公開コード',
	CASE_NAME TEXT COMMENT '事件名',
	PRECEDENT_REPORTS_KAN INT UNSIGNED COMMENT '判例集巻',
	PRECEDENT_REPORTS_GO INT UNSIGNED COMMENT '判例集号',
	PRECEDENT_REPORTS_KO INT UNSIGNED COMMENT '判例集頁',
	JUDGEMENT_REPORTS_GO INT UNSIGNED COMMENT '裁判集号',
	JUDGEMENT_REPORTS_KO INT UNSIGNED COMMENT '裁判集頁',
	JUDGEMENT_DATE DATE COMMENT '裁判年月日',
	ORIGINAL_JUDGEMENT_ID BIGINT UNSIGNED COMMENT '原審判決ID',
	CASE_NUMBER_ERA_CODE VARCHAR(10) NOT NULL COMMENT '元号コード',
	CASE_NUMBER_YEAR INT UNSIGNED NOT NULL COMMENT '事件番号年',
	CASE_MARK_ID INT UNSIGNED NOT NULL COMMENT '事件符号ID',
	CASE_NUMBER_SERIAL_NUMBER INT UNSIGNED NOT NULL COMMENT '事件番号連番',
	COURT_ID INT UNSIGNED NOT NULL COMMENT '裁判所ID',
	BENCH_CODE VARCHAR(10) COMMENT '法廷種別コード',
	JUDGEMENT_RESULT_CODE VARCHAR(10) COMMENT '判決結果コード',
	JUDGEMENT_TYPE_CODE VARCHAR(10) COMMENT '判決種別コード',
	SENTENCE TEXT COMMENT '判決文 : 取り込み時に判決文がないことを許容したい',
	PRIMARY KEY (JUDGEMENT_ID)
) COMMENT = '判決';


CREATE TABLE JUDGEMENT_SOURCE_REL
(
	JUDGEMENT_SOURCE_REL_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '判決取得元リレーションID',
	JUDGEMENT_ID BIGINT UNSIGNED NOT NULL COMMENT '判決ID',
	SOURCE_ID INT UNSIGNED NOT NULL COMMENT '取得元ID',
	SOURCE_JUDGEMENT_ID VARCHAR(100) NOT NULL COMMENT '取得元判決ID',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (JUDGEMENT_SOURCE_REL_ID)
) COMMENT = '判決取得元リレーション';


CREATE TABLE JUDGEMENT_USER_FAVORITE_REL
(
	JUDGEMENT_USER_FAVORITE_REL_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '判決ユーザーお気に入りリレーションID',
	JUDGEMENT_ID BIGINT UNSIGNED NOT NULL COMMENT '判決ID',
	USER_ID INT UNSIGNED NOT NULL COMMENT 'ユーザーID',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (JUDGEMENT_USER_FAVORITE_REL_ID),
	CONSTRAINT UQ_JUDGEMENT_USER_FAVORITE_REL UNIQUE (JUDGEMENT_ID, USER_ID)
) COMMENT = '判決ユーザーお気に入りリレーション';


CREATE TABLE LOGIN_HISTORY
(
	LOGIN_HISTORY_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ログイン履歴ID',
	LOGIN_DATETIME DATETIME NOT NULL COMMENT 'ログイン日時',
	USER_ID INT UNSIGNED NOT NULL COMMENT 'ユーザーID',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (LOGIN_HISTORY_ID)
) COMMENT = 'ログイン履歴';


CREATE TABLE SOURCE
(
	SOURCE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '取得元ID',
	SOURCE_NAME VARCHAR(100) NOT NULL UNIQUE COMMENT '取得元名',
	SOURCE_ALIAS VARCHAR(100) NOT NULL UNIQUE COMMENT '取得元別名',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (SOURCE_ID)
) COMMENT = '取得元';


CREATE TABLE USER
(
	USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
	MAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE COMMENT 'メールアドレス',
	PASSWORD VARCHAR(255) NOT NULL COMMENT 'パスワード',
	USER_STATUS_CODE VARCHAR(10) NOT NULL COMMENT 'ユーザーステータスコード',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (USER_ID)
) COMMENT = 'ユーザー';


CREATE TABLE USER_STATUS_HISTORY
(
	USER_STATUS_HISTORY_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_ID INT UNSIGNED NOT NULL COMMENT 'ユーザーID',
	USER_NEW_STATUS_CODE VARCHAR(10) NOT NULL COMMENT 'ユーザー新ステータスコード',
	USER_STATUS_UPDATE_DATETIME DATETIME NOT NULL COMMENT 'ユーザーステータス更新日時 : ユーザーステータスが更新された日時',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードが登録された日時',
	REGISTER_USER VARCHAR(200) NOT NULL COMMENT '登録ユーザー : レコードを登録したユーザー',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードが(最後に)更新された日時',
	UPDATE_USER VARCHAR(200) NOT NULL COMMENT '更新ユーザー : レコードを(最後に)更新したユーザー',
	VERSION_NO BIGINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'バージョン番号 : バージョン番号',
	PRIMARY KEY (USER_STATUS_HISTORY_ID)
) COMMENT = 'ユーザーステータス履歴';



/* Create Foreign Keys */

ALTER TABLE JUDGEMENT
	ADD CONSTRAINT FK_JUDGEMENT_CASE_MARK FOREIGN KEY (CASE_MARK_ID)
	REFERENCES CASE_MARK (CASE_MARK_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT
	ADD CONSTRAINT FK_JUDGEMENT_CLS_BENCH FOREIGN KEY (BENCH_CODE)
	REFERENCES CLS_BENCH (BENCH_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CASE_MARK
	ADD CONSTRAINT FK_CASE_MARK_CLS_CASE_CATEGORY FOREIGN KEY (CASE_CATEGORY_CODE)
	REFERENCES CLS_CASE_CATEGORY (CASE_CATEGORY_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CASE_MARK
	ADD CONSTRAINT FK_CASE_MARK_CLS_COURT_TYPE FOREIGN KEY (COURT_TYPE_CODE)
	REFERENCES CLS_COURT_TYPE (COURT_TYPE_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COURT
	ADD CONSTRAINT FK_COURT_CLS_COURT_TYPE FOREIGN KEY (COURT_TYPE_CODE)
	REFERENCES CLS_COURT_TYPE (COURT_TYPE_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT
	ADD CONSTRAINT FK_JUDGEMENT_CLS_ERA FOREIGN KEY (CASE_NUMBER_ERA_CODE)
	REFERENCES CLS_ERA (ERA_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT
	ADD CONSTRAINT FK_JUDGEMENT_CLS_JUDGEMENT_RESULT FOREIGN KEY (JUDGEMENT_RESULT_CODE)
	REFERENCES CLS_JUDGEMENT_RESULT (JUDGEMENT_RESULT_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT
	ADD CONSTRAINT FK_JUDGEMENT_CLS_JUDGEMENT_TYPE FOREIGN KEY (JUDGEMENT_TYPE_CODE)
	REFERENCES CLS_JUDGEMENT_TYPE (JUDGEMENT_TYPE_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER
	ADD CONSTRAINT FK_USER_CLS_USER_STATUS FOREIGN KEY (USER_STATUS_CODE)
	REFERENCES CLS_USER_STATUS (USER_STATUS_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_STATUS_HISTORY
	ADD CONSTRAINT FK_USER_STATUS_HISTORY_CLS_USER_STATUS FOREIGN KEY (USER_NEW_STATUS_CODE)
	REFERENCES CLS_USER_STATUS (USER_STATUS_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT
	ADD CONSTRAINT FK_JUDGEMENT_COURT FOREIGN KEY (COURT_ID)
	REFERENCES COURT (COURT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT
	ADD CONSTRAINT FK_JUDGEMENT_JUDGEMENT FOREIGN KEY (ORIGINAL_JUDGEMENT_ID)
	REFERENCES JUDGEMENT (JUDGEMENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT_SOURCE_REL
	ADD CONSTRAINT FK_JUDGEMENT_SOURCE_REL_JUDGEMENT FOREIGN KEY (JUDGEMENT_ID)
	REFERENCES JUDGEMENT (JUDGEMENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT_USER_FAVORITE_REL
	ADD CONSTRAINT FK_JUDGEMENT_USER_FAVORITE_REL_JUDGEMENT FOREIGN KEY (JUDGEMENT_ID)
	REFERENCES JUDGEMENT (JUDGEMENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT_SOURCE_REL
	ADD CONSTRAINT FK_JUDGEMENT_SOURCE_REL_SOURCE FOREIGN KEY (SOURCE_ID)
	REFERENCES SOURCE (SOURCE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE JUDGEMENT_USER_FAVORITE_REL
	ADD CONSTRAINT FK_JUDGEMENT_USER_FAVORITE_REL_USER FOREIGN KEY (USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOGIN_HISTORY
	ADD CONSTRAINT FK_LOGIN_HISTORY_USER FOREIGN KEY (USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_STATUS_HISTORY
	ADD CONSTRAINT FK_USER_STATUS_HISTORY_USER FOREIGN KEY (USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



